### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [pranavMekkoth1/Lab1-tutorial#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
  - please format all terminal commands as code (e.g., cd, ls, ssh [your course specific account], etc)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
  - please include the method (+ screenshot) that you tried for this part of lab 1: Use what you’ve learned to come up with the most pleasant process you can for making a local edit to WhereAmI.java, then copying it to the remote server and running it.
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by pranavMekkoth1** [comment]
I am not sure what is mean by the second check mark. Could you clarify what it means to format all terminal commands as code? Also what is meant by the second to last unchecked box?

**Comment by farnaf** [comment]
Hi there! 
- You can use backticks to format all terminal commands in your lab report as code. For example, change mkdir to `mkdir`, ssh-keygen to `ssh-keygen` and so on - similar to how [part 4 of lab 1](https://ucsd-cse15l-w22.github.io/week/week1/#part-4--run-some-commands) is formatted.
-  What we're looking for in the last part is what **you** tried in [this part of lab 1](https://ucsd-cse15l-w22.github.io/week/week1/#part-7-making-remote-running-even-more-pleasant). Using the hints that we provided, show the process you (and your lab group) came up with to make a local edit to WhereAmI.java, then copy it to the remote server and compile/run it there.

**Comment by pranavMekkoth1** [comment]
Also, the professor said on piazza that all the lab parts should be on one page.  Should I copy the lab instructions to a new page or and put a link to it on the index page? I am a bit confused by that

**Comment by pranavMekkoth1** [comment]
There is no regrade request button under lab report 1 on grade scope. Even after I click on individual questions. I think it may be because it says submitted and not graded but not sure.

**Comment by farnaf** [comment]
We haven't published grades yet, but I updated the above rubric with the fixes you made so far (:

The second to last requirement is not quite correct yet. Currently, the last step shows the java program running locally (on _your_ computer). Instead, come up with a command that once typed in your local terminal, the java program runs on the server (the computer you access when you ssh with your 15L account). 

To do the above task the long way, we can (1) use scp to copy the java file over to the server (2) ssh into 15L account (3) compile the copied java file (4) run it. The goal of the last step is to come up with an optimized version of these 4 steps.

**Comment by pranavMekkoth1** [comment]
Ok. I just changed it. 
Once the tasks above are all marked correct, will I still have to complete a regrade request?

**Comment by farnaf** [comment]
Great! Yes, now that we've published grades could you submit a regrade request?
